### PR TITLE
Add shell scripts to "source code"

### PR DESCRIPTION
**Pull request by lmperry**
A number of users are uploading shell scripts, which are not getting typed and cannot be viewed in the UI.

### Review Checklist

- Tests were added to cover all code changes
- Documentation was added / updated
- Code and tests follow standards in CONTRIBUTING.md

### CODE REVIEW

**Comment by nagem** [comment]
@lmperry Let me know if you want to re-type existing or just properly type all newly uploaded `.sh` files.

**Comment by lmperry** [comment]
I don't know how common these are at this point, but it would be great to re-type the existing files. Thanks!

**Comment by nagem** [comment]
@hkethi002 could you write a quick db update script? Just set it if it's not there.

**Comment by nagem** [comment]
@hkethi002 this will need to get rebased FYI

**Pull request merged**
